default_platform(:android)

platform :android do
  desc "Upload AAB to Google Play internal testing track"
  lane :internal do
    upload_to_play_store(
      track: "internal",
      aab: ENV["AAB_PATH"],
      package_name: ENV["PACKAGE_NAME"],
      json_key: ENV["PLAY_JSON_KEY_FILE"],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
