default_platform(:android)

platform :android do
  desc "Upload AAB to Google Play internal testing track (+ upload changelog from metadata_path)"
  lane :internal do
    upload_to_play_store(
      track: "internal",
      aab: ENV["AAB_PATH"],
      package_name: ENV["PACKAGE_NAME"],
      json_key: ENV["PLAY_JSON_KEY_FILE"],

      # Only changelogs, skip everything else
      metadata_path: ENV["METADATA_PATH"],
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Upload build to Google Play Internal App Sharing and print URL"
  lane :ias do
    url = upload_to_play_store_internal_app_sharing(
      package_name: ENV["PACKAGE_NAME"],
      json_key: ENV["PLAY_JSON_KEY_FILE"],
      aab: ENV["AAB_PATH"]
    )
    UI.message("IAS_URL=#{url}")
  end
end
