default_platform(:ios)

platform :ios do
  desc "Upload IPA to TestFlight (API key auth)"
  lane :testflight do
    upload_to_testflight(
      api_key_path: ENV["ASC_API_KEY_JSON"],
      ipa: ENV["IPA_PATH"],
      skip_waiting_for_build_processing: true
    )
  end
end
